// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrznR9u9Kgo15TtgEE8X_98UmXho-CKI',
    appId: '1:332250589415:web:b53eaaa931f92c07a6da42',
    messagingSenderId: '332250589415',
    projectId: 'hoopsbets',
    authDomain: 'hoopsbets.firebaseapp.com',
    storageBucket: 'hoopsbets.firebasestorage.app',
    measurementId: 'G-D0FSW7Z206',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPikQb5BSxMMyQv7fqc1THzMlCFRXhD4g',
    appId: '1:332250589415:android:f17e59cb47f4f09aa6da42',
    messagingSenderId: '332250589415',
    projectId: 'hoopsbets',
    storageBucket: 'hoopsbets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEqsKLULKZ0eYXcqmXoftK6xYtoXWQ1fw',
    appId: '1:332250589415:ios:a95d5997323db9d9a6da42',
    messagingSenderId: '332250589415',
    projectId: 'hoopsbets',
    storageBucket: 'hoopsbets.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEqsKLULKZ0eYXcqmXoftK6xYtoXWQ1fw',
    appId: '1:332250589415:ios:a95d5997323db9d9a6da42',
    messagingSenderId: '332250589415',
    projectId: 'hoopsbets',
    storageBucket: 'hoopsbets.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrznR9u9Kgo15TtgEE8X_98UmXho-CKI',
    appId: '1:332250589415:web:96db451327751e6ea6da42',
    messagingSenderId: '332250589415',
    projectId: 'hoopsbets',
    authDomain: 'hoopsbets.firebaseapp.com',
    storageBucket: 'hoopsbets.firebasestorage.app',
    measurementId: 'G-H0BFGZ8E2Z',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDVrznR9u9Kgo15TtgEE8X_98UmXho-CKI',
    appId: '1:332250589415:web:96db451327751e6ea6da42',
    messagingSenderId: '332250589415',
    projectId: 'hoopsbets',
    authDomain: 'hoopsbets.firebaseapp.com',
    storageBucket: 'hoopsbets.firebasestorage.app',
    measurementId: 'G-H0BFGZ8E2Z',
  );

}